#ifndef MUX_H_
#define MUX_H_

#include <stdint.h>

#define MUX_REF_RESISTOR_33_OHM_UPPER_BOUND 20
#define MUX_REF_RESISTOR_100_OHM_UPPER_BOUND 60
#define MUX_REF_RESISTOR_470_OHM_UPPER_BOUND 300
#define MUX_REF_RESISTOR_1_KOHM_UPPER_BOUND 600
#define MUX_REF_RESISTOR_10_KOHM_UPPER_BOUND 6000
#define MUX_REF_RESISTOR_100_KOHM_UPPER_BOUND 60000
#define MUX_REF_RESISTOR_560_KOHM_UPPER_BOUND 300000
#define MUX_REF_RESISTOR_1120_KOHM_UPPER_BOUND 1120000

typedef enum {
    MUX_REF_RESISTOR_33_OHM = 0,
    MUX_REF_RESISTOR_100_OHM,
    MUX_REF_RESISTOR_470_OHM,
    MUX_REF_RESISTOR_1_KOHM,
    MUX_REF_RESISTOR_10_KOHM,
    MUX_REF_RESISTOR_100_KOHM,
    MUX_REF_RESISTOR_560_KOHM,
    MUX_REF_RESISTOR_1120_KOHM,
    NUM_MUX_REF_RESISTORS,
} mux_ref_resistor;

void mux_init(void);

uint32_t mux_convert_resistance(mux_ref_resistor resistor);

void mux_select(mux_ref_resistor resistor);

#endif /* MUX_H_ */
